# Generated by Django 5.2.8 on 2025-11-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_testresult_useranswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="main.question",
            ),
        ),
    ]
