# Generated by Django 5.2.8 on 2025-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_customuser_options_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="group",
        ),
        migrations.AddField(
            model_name="test",
            name="groups",
            field=models.ManyToManyField(
                related_name="tests", to="main.group", verbose_name="Группы"
            ),
        ),
    ]
