# Generated by Django 5.2.8 on 2025-11-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_test_group_test_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={},
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("choice", "Вариант ответа"), ("open", "Открытый вопрос")],
                default="choice",
                max_length=10,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="open_answer",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ответ на открытый вопрос"
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="text_answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.answeroption",
            ),
        ),
    ]
