# Generated by Django 5.2.8 on 2025-11-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_question_options_question_question_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="selected_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_answers",
                to="main.answeroption",
            ),
        ),
    ]
