# Generated by Django 5.2.8 on 2025-12-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_question_options_question_question_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_text_answer",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Правильный текстовый ответ (для открытых вопросов)",
            ),
        ),
    ]
