# Generated by Django 5.2.8 on 2025-12-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_question_correct_text_answer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="selected_answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_answers",
                to="main.answeroption",
            ),
        ),
    ]
