# Generated by Django 5.2.8 on 2025-11-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_useranswer_selected_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название уровня"),
                ),
                (
                    "min_percentage",
                    models.PositiveIntegerField(verbose_name="Минимальный %"),
                ),
                (
                    "max_percentage",
                    models.PositiveIntegerField(verbose_name="Максимальный %"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание уровня"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Рекомендации"),
                ),
            ],
            options={
                "verbose_name": "Уровень выполнения",
                "verbose_name_plural": "Уровни выполнения",
                "ordering": ["min_percentage"],
            },
        ),
        migrations.AddField(
            model_name="testresult",
            name="performance_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.performancelevel",
                verbose_name="Уровень",
            ),
        ),
    ]
