# Generated by Django 5.2.8 on 2025-12-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_useranswer_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("min_percent", models.PositiveIntegerField()),
                ("max_percent", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("recommendations", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="main.test",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
